namespace ijw.Next.IO.CsvReader.xTest {
    internal class CsvTestClass {
        public string 井名 { get; set; }
        public string 区块 { get; set; }
        public float 起始井深 { get; set; }
        public float 终止井深 { get; set; }
        public string 地层名称 { get; set; }
        public string 岩性描述 { get; set; }
        public float 孔隙压力上限 { get; set; }
        public float 孔隙压力下限 { get; set; }
        public float 孔隙压力平均值 { get; set; }
        public float 破裂压力上限 { get; set; }
        public float 破裂压力下限 { get; set; }
        public float 破裂压力平均值 { get; set; }
        public float 坍塌压力上限 { get; set; }
        public float 坍塌压力下限 { get; set; }
        public float 坍塌压力平均值 { get; set; }
        public float 泥质含量上限 { get; set; }
        public float 泥质含量下限 { get; set; }
        public float 泥质含量平均值 { get; set; }
        public float 渗透率上限 { get; set; }
        public float 渗透率下限 { get; set; }
        public float 渗透率平均值 { get; set; }
        public float 孔隙度上限 { get; set; }
        public float 孔隙度下限 { get; set; }
        public float 孔隙度平均值 { get; set; }
        public float 抗压强度上限 { get; set; }
        public float 抗压强度下限 { get; set; }
        public float 抗压强度平均值 { get; set; }
        public float 是否过断层 { get; set; }
        public int 裂缝 { get; set; }
        public int 溶洞 { get; set; }
        public int 不整合 { get; set; }
        public string 钻头类型 { get; set; }
        public float 钻头尺寸 { get; set; }
        public string 钻具组合类型 { get; set; }
        public string 钻井方式 { get; set; }
        public float 最大造斜率 { get; set; }
        public string 钻井工艺 { get; set; }
        public string 是否使用提速工具 { get; set; }
        public string 钻井液体系 { get; set; }
        public float 钻井液密度上限 { get; set; }
        public float 钻井液密度下限 { get; set; }
        public float 钻井液密度平均值 { get; set; }
        public float 粘度上限 { get; set; }
        public float 粘度下限 { get; set; }
        public float 粘度平均值 { get; set; }
        public float 动切力上限 { get; set; }
        public float 动切力下限 { get; set; }
        public float 动切力平均值 { get; set; }
        public float 钻压上限 { get; set; }
        public float 钻压下限 { get; set; }
        public float 钻压平均值 { get; set; }
        public float 转速上限 { get; set; }
        public float 转速下限 { get; set; }
        public float 转速平均值 { get; set; }
        public float 排量上限 { get; set; }
        public float 排量下限 { get; set; }
        public float 排量平均值 { get; set; }
        public float 平均钻速 { get; set; }
        public int 复杂发生次数 { get; set; }
    }
}